name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache local repository
      uses: actions/cache@v3
      with:
        path: ~/.cache/objectos
        key: ${{ runner.os }}-objectos-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-objectos-
        
    - name: Run tests
      run: make test
